name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build \
          -t ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:backend-latest \
          ./Backend

      - name: Push Backend Image
        run: |
          docker push \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:backend-latest

      - name: Build Frontend Image
        run: |
          docker build \
          --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
          -t ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:frontend-latest \
          ./Frontend

      - name: Push Frontend Image
        run: |
          docker push \
          ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:frontend-latest

  deploy:

    needs: build-and-push

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create Backend .env
        run: |
          cat <<EOF > Backend/.env
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
          PORT=${{ secrets.PORT }}
          EOF

      - name: Create Compose Environment
        run: |
          cat <<EOF > .env
          AWS_ECR_LOGIN_URI=${{ secrets.AWS_ECR_LOGIN_URI }}
          ECR_REPOSITORY_NAME=${{ secrets.ECR_REPOSITORY_NAME }}
          EOF

      - name: Stop Existing Containers
        run: docker compose down || true

      - name: Pull Latest Images
        run: docker compose pull

      - name: Start Containers
        run: docker compose up -d